/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Smktelkom
 */
public class Test1 extends javax.swing.JFrame {

    /**
     * Creates new form Test1
     */
    public Test1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        Absen = new javax.swing.JLabel();
        Mapel = new javax.swing.JLabel();
        nilai = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        absen = new javax.swing.JTextField();
        mapel = new javax.swing.JTextField();
        BtnProses = new javax.swing.JButton();
        Nilai = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Hasil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Penilaian");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 10, 60, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Hasil");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 234, 34, 16);

        Nama.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Nama.setText("Nama");
        getContentPane().add(Nama);
        Nama.setBounds(100, 60, 34, 14);

        Absen.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Absen.setText("Absen");
        getContentPane().add(Absen);
        Absen.setBounds(100, 100, 50, 14);

        Mapel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Mapel.setText("Matpel");
        getContentPane().add(Mapel);
        Mapel.setBounds(100, 140, 50, 14);
        getContentPane().add(nilai);
        nilai.setBounds(170, 170, 140, 30);

        nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaActionPerformed(evt);
            }
        });
        getContentPane().add(nama);
        nama.setBounds(170, 50, 140, 30);
        getContentPane().add(absen);
        absen.setBounds(170, 90, 140, 30);
        getContentPane().add(mapel);
        mapel.setBounds(170, 130, 140, 30);

        BtnProses.setText("PROSES");
        BtnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProsesActionPerformed(evt);
            }
        });
        getContentPane().add(BtnProses);
        BtnProses.setBounds(160, 210, 71, 23);

        Nilai.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        Nilai.setText("Nilai");
        getContentPane().add(Nilai);
        Nilai.setBounds(100, 180, 34, 14);

        Hasil.setColumns(20);
        Hasil.setRows(5);
        jScrollPane1.setViewportView(Hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 260, 280, 110);

        setBounds(0, 0, 416, 438);
    }// </editor-fold>//GEN-END:initComponents

    private void namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namaActionPerformed

    private void BtnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProsesActionPerformed
        // TODO add your handling code here:
        String Nama = nama.getText();
        int Absen = Integer.parseInt(absen.getText());
        String Mapel = mapel.getText();
        int Nilai = Integer.parseInt(nilai.getText());
        Hasil.append("Nama Siswa : "+Nama+"\n");
        Hasil.append("Nomor Absen : "+Absen+"\n");
        Hasil.append("Mata Pelajaran : "+Mapel+"\n");
        Hasil.append("Nilai : "+Nilai+"\n");
        
        if(Nilai >=86 && Nilai <=100 ){
            Hasil.append("Predikat : Sempurna\n");
        } else if (Nilai >=75 && Nilai <=85){
            Hasil.append("Predikat : Lulus\n");
        }else if(Nilai <=74){
            Hasil.append("Predikat : Tidak Lulus\n");
        }
        else{
            Hasil.append("Predikat : Nilai Salah\n");
        }
        
    }//GEN-LAST:event_BtnProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Absen;
    private javax.swing.JButton BtnProses;
    private javax.swing.JTextArea Hasil;
    private javax.swing.JLabel Mapel;
    private javax.swing.JLabel Nama;
    private javax.swing.JLabel Nilai;
    private javax.swing.JTextField absen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mapel;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nilai;
    // End of variables declaration//GEN-END:variables
}
